spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #解决数据库下滑线在java对象中变量名驼峰无法对应问题
    #否则打印的查询结果中就会有null值
    #Category{id=100001, parentId=null, name='家用电器', status=1, sortOrder=null, createTime=null, updateTime=null}
  mapper-locations: classpath:mappers/*.xml #无此mapper无法映射BindingException: Invalid bound statement (not found)
wx:
  appId: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://yxq520.natapp1.cc/pay/notify
  returnUrl: http://127.0.0.1